apiVersion: apps/v1
kind: Deployment
metadata:
  name: carpooling-deployment
  labels:
    app: carpooling #key-value pair. Identifier which should be meaningful. Example "env" : "dev"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carpooling
  template:
    metadata:
      labels:
        app: carpooling
    spec:
      containers:
      - name: carpooling
        image: carpooling:89
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING.DATASOURCE.USERNAME
          valueFrom:
            secretKeyRef:
              name: carpooling-secret
              key: db-username
        - name: SPRING.DATASOURCE.PASSWORD
          valueFrom:
            secretKeyRef:
              name: carpooling-secret
              key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: carpooling-service
spec:
  selector:
    app: carpooling
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010