apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://ZhivkoDevOpsProjects@dev.azure.com/ZhivkoDevOpsProjects/Carpooling/_git/Carpooling
  password: 37yhw2foqzbs3emhjhvbky6dbyhr2ksf7szfjzs25u6yhoahoqja
  username: zh.zhelev
