apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: carpooling-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ZhivkoDevOpsProjects@dev.azure.com/ZhivkoDevOpsProjects/Carpooling/_git/Carpooling
    targetRevision: HEAD
    path: k8s-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: carpooling
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
