apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJ6aHpoZWxldiIsInBhc3N3b3JkIjoiZGNrcl9wYXRfbkZ0Wk0zbVpGNE5vamlqUGZET2lDay14eUpNIiwiYXV0aCI6ImVtaDZhR1ZzWlhZNlpHTnJjbDl3WVhSZmJrWjBXazB6YlZwR05FNXZhbWxxVUdaRVQybERheTE0ZVVwTiJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2023-01-25T15:24:28Z"
  name: docker-secrets
  namespace: default
  resourceVersion: "2878"
  uid: 59dabf28-ad47-4e13-acda-6d588f065bbb
type: kubernetes.io/dockerconfigjson