apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: mariadb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi