apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: mariadb
spec:
  replicas: 1 #If we want multiple replicas we need to use ReplicaSet instead of Deployment
  selector:
    matchLabels: # All Pods witch label "mariadb" belong to this Deployment
      app: mariadb
  template: #Configuration for Pod
    metadata: #has its own metadata and spec
      labels:
        app: mariadb
    spec:
      containers: #We can have more than one container, but mostly have only one
      - name: mariadb #mongodb in the example
        image: mariadb:latest #
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: carpooling-secret
              key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306